<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <!-- 
        视频地址：https://www.bilibili.com/video/BV1GA411x7z1?p=2&spm_id_from=pageDriver&vd_source=b889f2895dcb3d033f7c73efe2d87d1f
        1、promise
          * promise是一个构造函数
          * （重点！！！！！！）是ES6引入用来解决回调地狱（回调函数嵌套：不便阅读，不便异常处理）
          * （重点！！！！！！）支持链式调用
        2、promise的状态[Promise.State]
          * 状态是promise实例的一个属性，表示的是
          * 状态属性的值
            * pending
            * resolved /fulfilled
            * rejected
          * 状态的变化
            * 只能从pending -> resolved
            * 或者从pending -> rejected
            * 且状态只能只能变更一次，不能在更改
        3、promise对象的值 [Promise.Result]
          * 保存着对象[成功/失败的]结果
            * resolve执行后的结果
            * reject执行后的结果
        4、Promise的工作流程
          * new Promise()创建一个实例对象
          * 在内部执行异步的操作
          * 成功，promise对象状态变更为resolved, 回调onResolved()函数（then）
          * 失败，promise对象状态变更为rejected,  回调onRejected()函数（then）
          * then方法返回的是一个新的promise对象，支持继续链式回调
        5、API
          * 构造函数Promise()
            * new Promise((resolve, reject) => {} )实例化对象
            * executor函数，执行器是一个函数 (resolve, reject) => {}
            * resolve函数，是内部定义成功的时候，调用的函数 value => {}
            * reject函数，是内部定义失败的时候，调用的函数 error => {}
            * 注意！！！： executor会在promise内部立即同步调用；异步操作在执行器中执行
          * Promise.prototype.then方法
            * 执行resove之后的回调函数
            * Promise.prototype.then((onResolved, onRejected) => {})
              * onResolved函数，成功之后的回调
              * onRejected函数，失败之后的回调
              * 返回一个新的promise对象
          * Promise.prototype.catch()
            * 执行reject之后的回调函数
          * Promise.prototype.finally()
            * finally方法在promise结束后，无论是成功还是失败都会执行的函数
          *******注意：以下方法是属于Promise构造函数对象的；上边的时候属于实例对象的，是挂在原型上的**************************************************************
          * Promise.resolve()方法
            * 参数(value) => {}
              * 如果传入的参数是非promise对象，则返回的是一个成功的promise对象
              * 如果传入的参数是promise对象，则参数返回的结果就是决定了resolve的结果
            * 返回一个成功或者失败的promise对象
          * Promise.reject()方法
            * 参数(reason) => {}， 失败的原因
            * 返回一个失败的promise对象
          * Promise.all()方法
            * 参数(promises) => {}, promises包含多个promise实例对象的数组
            * 返回一个新的Promise对象，如果都成功返回的是成功的数组，如果有一个失败了，返回的是失败的那个的结果
          * Promise.race()方法
            * 参数(promises) => {}, promises包含多个promise实例对象的数组
            * 结果状态：谁先状态，结果谁的
          * Promise.any()方法
            * 参数(promises) => {}, promises包含多个promise实例对象的数组
            * 结果状态：任何一个执行成功了，就返回成功的状态，都没有成功返回决绝的状态
          * Promise.allSettled()方法
            * 参数(promises) => {}, promises包含多个promise实例对象的数组
            * 结果状态：返回所有promise的执行结果
        6、改变状态的方法
          * resolve
          * reject
          * 抛出错误
        7、promise对象绑定多个回调函数是都执行吗？
          * 是的
        8、then方法的链式调用
        9、异常穿透
          * 就是只需要在最后的位置指定失败之后的回调就可以，其中任何一处出现错误就会被捕获
        10、如何中断promise的链式调用
          * 第一个执行器中返回一个pending状态的promise即可


     -->
    <script>
      // 基本的用法
      const p = new Promise((resolve, reject) => {
        // 执行器函数中的操作都是同步的
        // 输出的结果 1111 3333 2222
        console.log(1111);
        resolve(2222); // 返回3333
        console.log(3333);
        // resolve("errror");
      })
        .then((value) => {
          console.log(value, "value"); // 在异步操作中打印3333
        })
        .catch((error) => {
          console.log(error, "error");
          resolve("jdjdjdjd");
        })
        .finally(() => {
          console.log("怎么样都执行～～～～～");
        });
      // 2、Promise.resolve()
      // 非promise对象
      const p2 = Promise.resolve("1111");
      p2.then((value) => {
        console.log(value, "p2");
      });
      // promise对象
      const p3 = Promise.resolve(
        new Promise((resolve, reject) => {
          // resolve("p3");
          reject("p3");
        })
      );
      console.log(p3, "p3");
      p3.catch((reason) => {
        console.log(reason, "p3 reason");
      });
      p3.then((value) => {
        console.log(value, "p3 value");
      });
      // 3、Promise.reject()
      // 非promise对象
      const p4 = Promise.reject("p4");
      p4.catch((reason) => {
        console.log(reason, "reason");
      });
      // promise对象
      const p5 = Promise.reject(
        new Promise((resolve, reject) => {
          resolve("p5");
        })
      );
      console.log(p5, "p5");
      p5.catch((reason) => {
        console.log(reason, "reason");
      });

      const pErr = new Promise((resolve, reject) => {
        reject("race 总是失败");
      });

      const pSlow = new Promise((resolve, reject) => {
        setTimeout(resolve, 500, "race 最终完成");
      });

      const pFast = new Promise((resolve, reject) => {
        setTimeout(resolve, 100, "race 很快完成");
      });
      //4、Promise.all()
      Promise.all([pErr, pSlow, pFast])
        .then((values) => {
          console.log(values, "all success");
        })
        .catch((error) => {
          console.log(error, "all failed");
        });
      //5、Promise.race()
      Promise.race([pErr, pSlow, pFast])
        .then((values) => {
          console.log(values, "race success");
        })
        .catch((error) => {
          console.log(error, "all failed");
        });
      //6、Promise.race()
      Promise.any([pErr, pSlow, pFast])
        .then((value) => {
          console.log(value);
          // pFast fulfils first
        })
        .catch((error) => {
          console.log(error);
        });
      Promise.any([pErr])
        .then((value) => {
          console.log(value);
          // pFast fulfils first
        })
        .catch((error) => {
          console.log(error);
        });
      //7、Promise.allSettled()
      Promise.allSettled([pErr, pSlow, pFast]).then((results) =>
        results.forEach((result) => console.log(result.status, "result"))
      );

      // 8、链式调用
      new Promise((resolve, reject) => {
        resolve(123);
      })
        .then((value) => {
          // 改变状态
          // return 123;
          // return Promise.resolve("345");
          // throw new Error("错误");
          return new Promise((resolve, reject) => {
            resolve("789");
          });
        })
        .then((value) => {
          console.log(value, "链式调用成功");
          setTimeout(() => {
            console.log("链式调用成功 延迟");
          });
        })
        .then((value) => {
          console.log(value, "hahahaha"); // undefined
        })
        .catch((error) => {
          console.log(error, "链式调用错误");
        });
      // 9、中断链式调用
      new Promise((resolve, reject) => {
        resolve(123);
      })
        .then((value) => {
          // 改变状态
          // return 123;
          // return Promise.resolve("345");
          // throw new Error("错误");
          return new Promise((resolve, reject) => {});
        })
        .then((value) => {
          console.log(value, "中断啦");
        })
        .then((value) => {
          console.log(value, "hahahaha"); // undefined
        })
        .catch((error) => {
          console.log(error, "链式调用错误");
        });
    </script>
  </body>
</html>
